ports:
  - port: 8000
    onOpen: open-preview
    
tasks:
  - init: >
      python3 -m pip install -r requirements.txt
    command: >
      sphinx-autobuild -b html --host 0.0.0.0 --port 8000 ./source ./build/html/
    